
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato
  namespace: produce-aisle
spec:
  selector:
    matchLabels:
      app: tomato
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
        greymatter.io/configure-sidecar: "true"
      labels:
        app: tomato
    spec:
      containers:
        - name: tomato
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080"]

