apiVersion: v1
data:
  index.html: An apple a day keeps the dentist away.
kind: ConfigMap
metadata:
  name: apple-web
  namespace: examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  namespace: examples
spec:
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
      labels:
        app: apple
    spec:
      containers:
        - name: apple
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080", "--directory", "web"]
          volumeMounts:
            - name: web-volume
              mountPath: /web
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: web-volume
          configMap:
            name: apple-web
---
apiVersion: v1
data:
  index.html: This is totally bananas.
kind: ConfigMap
metadata:
  name: banana-web
  namespace: examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana
  namespace: examples
spec:
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
      labels:
        app: banana
    spec:
      containers:
        - name: banana
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080", "--directory", "web"]
          volumeMounts:
            - name: web-volume
              mountPath: /web
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: web-volume
          configMap:
            name: banana-web
---
apiVersion: v1
data:
  index.html: Everybody romaine calm!
kind: ConfigMap
metadata:
  name: lettuce-web
  namespace: examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lettuce
  namespace: examples
spec:
  selector:
    matchLabels:
      app: lettuce
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
      labels:
        app: lettuce
    spec:
      containers:
        - name: lettuce
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080", "--directory", "web"]
          volumeMounts:
            - name: web-volume
              mountPath: /web
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: web-volume
          configMap:
            name: lettuce-web
---
apiVersion: v1
data:
  index.html: You say Tomato, I say Tomato.
kind: ConfigMap
metadata:
  name: tomato-web
  namespace: examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato
  namespace: examples
spec:
  selector:
    matchLabels:
      app: tomato
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
      labels:
        app: tomato
    spec:
      containers:
        - name: tomato
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080", "--directory", "web"]
          volumeMounts:
            - name: web-volume
              mountPath: /web
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: web-volume
          configMap:
            name: tomato-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocerylist-edge
  namespace: examples
spec:
  selector:
    matchLabels:
      app: grocerylist-edge
  template:
    metadata:
      labels:
        app: grocerylist-edge
    spec:
      containers:
      - env:
        - name: XDS_CLUSTER
          value: grocerylist-edge
        - name: ENVOY_ADMIN_LOG_PATH
          value: /dev/stdout
        - name: PROXY_DYNAMIC
          value: "true"
        - name: XDS_ZONE
          value: default-zone
        - name: XDS_HOST
          value: controlensemble.greymatter.svc.cluster.local
        - name: XDS_PORT
          value: "50000"
        image: quay.io/greymatterio/gm-proxy:1.7.0
        imagePullPolicy: Always
        name: sidecar
        ports:
        - containerPort: 10808
          name: proxy
          protocol: TCP
        - containerPort: 8081
          name: metrics
          protocol: TCP
        resources: {}
      imagePullSecrets:
      - name: gm-docker-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grocerylist-edge
  namespace: examples
spec:
  ports:
  - name: ingress
    port: 10808
    protocol: TCP
    targetPort: 10808
  selector:
    greymatter.io/cluster: grocerylist-edge
  type: LoadBalancer