apiVersion: v1
kind: Namespace
metadata:
  name: examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  namespace: examples
spec:
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
        greymatter.io/configure-sidecar: "true"
      labels:
        app: apple
    spec:
      containers:
        - name: apple
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana
  namespace: examples
spec:
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
        greymatter.io/configure-sidecar: "true"
      labels:
        app: banana
    spec:
      containers:
        - name: banana
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lettuce
  namespace: examples
spec:
  selector:
    matchLabels:
      app: lettuce
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
        greymatter.io/configure-sidecar: "true"
      labels:
        app: lettuce
    spec:
      containers:
        - name: lettuce
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato
  namespace: examples
spec:
  selector:
    matchLabels:
      app: tomato
  template:
    metadata:
      annotations:
        greymatter.io/inject-sidecar-to: "8080"
        greymatter.io/configure-sidecar: "true"
      labels:
        app: tomato
    spec:
      containers:
        - name: tomato
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "8080"]
