#!/bin/bash
set -e

for dependency in git cue
do
    if ! which $dependency &> /dev/null; then
        echo "$dependency is missing from your \$PATH"
        exit 1
    fi
done

# Fetch our submodule from git
./scripts/update
