#!/bin/bash
set -e

# default build will export CUE into JSON.
cmd_default () {
    cue export EXPORT.cue -e mesh_configs
}

# fmt will run cue fmt against the entire cue project.
cmd_fmt () {
    cue fmt .
}

cmd_help () {
    echo "USAGE:"
    echo "./scripts/build [help|fmt]"
}

if [[ $# -eq "0" ]]; then
    cmd_default
    exit 0
fi
ARG=$1
shift
case $ARG in
    help|fmt)
        cmd_$ARG $@
        ;;
    *)
        echo "unknown arg: $ARG"
        cmd_help
        exit 1
        ;;
esac
